# alien :: zsh integration
# Source this from your .zshrc:
#   source <(alien init zsh)
#
# Provides:
#   * `alien <name>` and `a <name>` to add an alias from your last command
#   * Ctrl-G to open a fuzzy picker over your aliases
#   * automatic re-sourcing of aliases after every change

# --- config (override before sourcing) ----------------------------------
: ${ALIEN_HOME:="${XDG_CONFIG_HOME:-$HOME/.config}/alien"}
: ${ALIEN_KEYBIND:="^G"}            # Ctrl-G; set to "" to skip binding
: ${ALIEN_FZF_OPTS:=""}             # extra flags appended to fzf
: ${ALIEN_TRACK:=1}                 # set to 0 to disable usage tracking

# Source the active aliases on startup. The Go binary regenerates this file
# after every modification so it's always cheap and always current.
[[ -r "$ALIEN_HOME/aliases.sh" ]] && source "$ALIEN_HOME/aliases.sh"

# Index aliases the user already has defined in their rc files and plugins.
# We pipe `alias` (the shell builtin) into the binary, which merges them into
# the store with Source=shell so the picker can search them too. Stale rc
# entries get pruned automatically.
#
# We also tell the binary which files to grep for `alias name=` lines so it
# can fill the FROM column with a useful origin label (".zshrc", "omz:git",
# etc.) instead of a generic "shell".
if command -v alien >/dev/null 2>&1; then
  local _alien_rc=()
  local _f
  for _f in ~/.zshrc ~/.zshenv ~/.zprofile ~/.zlogin ~/.profile \
           ~/.aliases ~/.zsh_aliases; do
    [[ -r $_f ]] && _alien_rc+=$_f
  done
  if [[ -d ~/.oh-my-zsh ]]; then
    for _f in ~/.oh-my-zsh/lib/*.zsh(N) \
             ~/.oh-my-zsh/plugins/*/*.plugin.zsh(N) \
             ~/.oh-my-zsh/custom/*.zsh(N) \
             ~/.oh-my-zsh/custom/plugins/*/*.plugin.zsh(N); do
      _alien_rc+=$_f
    done
  fi
  ALIEN_RC_FILES="${(j.:.)_alien_rc}" alias 2>/dev/null | \
    ALIEN_RC_FILES="${(j.:.)_alien_rc}" command alien import-shell --quiet
  unset _alien_rc _f
  # Optional auto-pull (no-op unless enabled and throttle elapsed).
  command alien sync maybe-pull 2>/dev/null
fi

# ---------------- usage tracking -----------------------------------------
# Counts real alias invocations: preexec checks the first word of each
# command against the store's alias names (names.txt, regenerated by the
# binary on every change) and appends a hit to hits.log. Builtins only —
# zero forks, zero subshells on the non-hit path. `alien track flush` folds
# the log into usage.json on shell startup and after alien invocations.
#
# Known accuracy limits (fine for frequency telemetry): misses `sudo ll`,
# `VAR=1 ll`, and aliases mid-pipeline (`x | ll`). Set ALIEN_TRACK=0 to
# disable entirely.
typeset -gA _alien_names
_alien_load_names() {
  _alien_names=()
  [[ -r "$ALIEN_HOME/names.txt" ]] || return 0
  local _n
  while IFS= read -r _n; do
    [[ -n $_n ]] && _alien_names[$_n]=1
  done < "$ALIEN_HOME/names.txt"
  return 0
}

_alien_track_preexec() {
  local w=${1%%[[:space:]]*}
  if [[ -n $w && -n ${_alien_names[$w]} ]]; then
    print -r -- "$w" >> "$ALIEN_HOME/hits.log"
  fi
  return 0
}

if [[ "$ALIEN_TRACK" != 0 ]] && command -v alien >/dev/null 2>&1; then
  _alien_load_names
  autoload -Uz add-zsh-hook
  add-zsh-hook preexec _alien_track_preexec
  # Fold hits from previous sessions into usage.json.
  command alien track flush 2>/dev/null
fi

# `alien` shell function: captures the previous command via `fc -ln -1` so that
# `alien <name>` (with no explicit --cmd) can use it. Then re-sources the
# aliases file so the new alias is live immediately in this shell.
alien() {
  emulate -L zsh
  if (( $# == 0 )); then
    command alien
    return
  fi
  # `chain` needs more than the previous line — pipe a window of recent
  # history (newest first) into the binary so the TUI can pick from it.
  if [[ "$1" == "chain" ]]; then
    local rc=0
    # Both atuin and fc emit oldest-first; the binary reverses internally
    # to display newest-at-top. Just pipe raw.
    if command -v atuin >/dev/null 2>&1; then
      atuin history list --cmd-only --session 2>/dev/null \
        | tail -200 | command alien "$@"
    else
      fc -ln -50 2>/dev/null | command alien "$@"
    fi
    rc=$?
    [[ -r "$ALIEN_HOME/aliases.sh" ]] && source "$ALIEN_HOME/aliases.sh"
    return $rc
  fi
  local prev
  prev=$(fc -ln -1 2>/dev/null)
  prev=${prev##[[:space:]]##}
  command alien --prev-cmd "$prev" "$@"
  local rc=$?
  [[ -r "$ALIEN_HOME/aliases.sh" ]] && source "$ALIEN_HOME/aliases.sh"
  # Refresh the tracking name set (the alias list may have just changed)
  # and fold any pending hits, detached so it never blocks the prompt.
  if [[ "$ALIEN_TRACK" != 0 ]]; then
    _alien_load_names
    (command alien track flush 2>/dev/null &) 2>/dev/null
  fi
  # Background auto-push if enabled. Detached so a slow remote never blocks
  # the user's prompt.
  (command alien sync maybe-push 2>/dev/null &) 2>/dev/null
  return $rc
}

# `a` is the convenience shortcut. We use a function (not an alias) so it can
# accept arguments cleanly and so it can also launch the picker when called
# bare from a non-ZLE context.
a() {
  if (( $# == 0 )); then
    _alien_pick_cli
  else
    alien "$@"
  fi
}

# ---------------- fuzzy picker (ZLE widget) -----------------------------
#
# Bound to $ALIEN_KEYBIND (default Ctrl-G). Reads tab-delimited rows from
# `alien fzf` (col1 = name, col2 = pretty display) and dispatches based on
# which key the user pressed inside fzf:
#   enter -> run the alias's command in the current shell
#   tab   -> insert the alias name into the command line
#   e     -> open `alien edit <name>`
#   d     -> open `alien delete <name>`

_alien_run_fzf() {
  # Reset the active tab so each picker invocation starts on "all". Users
  # who hit `[` / `]` mid-session can move; we don't want stale state from
  # a previous picker session to silently filter the next one.
  command alien tab set all >/dev/null 2>&1

  command alien fzf --filter all 2>/dev/null | fzf \
    --ansi \
    --delimiter=$'\t' \
    --with-nth=2 \
    --header-lines=3 \
    --no-multi \
    --reverse \
    --height=50% \
    --info=inline \
    --pointer='›' \
    --marker='✓' \
    --prompt='👽 alien › ' \
    --color='border:bright-cyan,prompt:bright-cyan,pointer:bright-magenta,header:gray,info:gray,hl:bright-yellow,hl+:bright-yellow' \
    --expect='tab,ctrl-e,ctrl-d' \
    --bind '[:transform(alien tab prev)' \
    --bind ']:transform(alien tab next)' \
    ${=ALIEN_FZF_OPTS}
}

_alien_fzf_widget() {
  emulate -L zsh
  setopt local_options pipe_fail no_aliases

  local result key line name cmd
  result=$(_alien_run_fzf </dev/tty)
  local -a lines=("${(@f)result}")
  key=${lines[1]}
  line=${lines[2]}
  name=${line%%$'\t'*}

  if [[ -z "$name" ]]; then
    zle reset-prompt
    return 0
  fi

  case "$key" in
    "")
      # Put the alias name (not the expanded command) into the buffer and
      # submit. zsh's normal alias-expansion runs on accept-line, so the
      # behavior is identical to typing `<name><enter>` — including history:
      # `up-arrow` recalls the alias, not the unrolled command.
      BUFFER="$name"
      CURSOR=${#BUFFER}
      zle accept-line
      ;;
    tab)
      LBUFFER+="$name "
      zle redisplay
      ;;
    ctrl-e)
      zle -I
      command alien edit "$name"
      zle reset-prompt
      ;;
    ctrl-d)
      zle -I
      command alien delete "$name"
      zle reset-prompt
      ;;
  esac
}
zle -N _alien_fzf_widget

# Non-ZLE picker, used by `a` with no args. We're not inside a ZLE widget
# here, so we can't manipulate $BUFFER directly — but `print -z` pushes text
# onto the editor buffer stack, which becomes prefilled at the *next* prompt.
# That gives "tab" the same prefill behavior as the Ctrl-G widget, just
# delayed by one redraw.
_alien_pick_cli() {
  emulate -L zsh
  if ! command -v fzf >/dev/null 2>&1; then
    print -u2 "alien: fzf is required for the picker"
    return 1
  fi
  local result key line name cmd
  result=$(_alien_run_fzf)
  local -a lines=("${(@f)result}")
  key=${lines[1]}
  line=${lines[2]}
  name=${line%%$'\t'*}
  [[ -z "$name" ]] && return 0
  case "$key" in
    "")
      cmd=$(command alien get "$name") || return 0
      print -P "%F{8}» $name%f"
      # Record the alias name in history so ↑-arrow recalls "ll", not the
      # underlying `ls -alh`. We can't get true alias expansion from a
      # function call (we're not inside ZLE), so still eval the command.
      print -s -- "$name"
      eval -- "$cmd"
      ;;
    tab)
      # Prefill the next prompt with the alias name + a trailing space so
      # the user can keep typing args before hitting enter.
      print -z -- "$name "
      ;;
    ctrl-e)
      command alien edit "$name"
      ;;
    ctrl-d)
      command alien delete "$name"
      ;;
  esac
}

if [[ -n "$ALIEN_KEYBIND" ]]; then
  bindkey "$ALIEN_KEYBIND" _alien_fzf_widget
fi

# ---------------- completion -------------------------------------------
# When the user presses Tab on `a <TAB>` or `alien <TAB>`, jump straight into
# the fuzzy picker. They can still type subcommand names manually.
_alien_complete_widget() {
  local words=(${(z)BUFFER})
  if (( ${#words} <= 2 )) && [[ "${words[1]}" == (a|alien) ]]; then
    _alien_fzf_widget
  else
    zle expand-or-complete
  fi
}
zle -N _alien_complete_widget
# Disabled by default — uncomment to override Tab on `a`:
#bindkey '^I' _alien_complete_widget
