package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"
)

type Alias struct {
	Command   string    `json:"command"`
	Comment   string    `json:"comment,omitempty"`
	Enabled   bool      `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	UsedCount int       `json:"used_count,omitempty"`

	// Source identifies where the alias came from. The empty string is the
	// default ("user-managed"). "shell" means it was imported from the user's
	// running shell (their rc files); we surface it in the picker but never
	// write it to aliases.sh because the rc already defines it. "pack:<name>"
	// means it was installed via `alien ufo install <name>` and will be
	// removed cleanly by `alien ufo uninstall <name>`.
	Source string `json:"source,omitempty"`

	Tags []string `json:"tags,omitempty"`
}

// InstalledPack records the metadata of a pack install so we can do a clean
// uninstall later (delete only AliasNames, leaving user-renamed copies alone
// — those have their own Source string).
type InstalledPack struct {
	Name        string    `json:"name"`
	Version     string    `json:"version,omitempty"`
	Description string    `json:"description,omitempty"`
	Source      string    `json:"source,omitempty"` // origin: builtin, file path, URL
	InstalledAt time.Time `json:"installed_at"`
	AliasNames  []string  `json:"alias_names"`
}

type Store struct {
	Version int                      `json:"version"`
	Aliases map[string]Alias         `json:"aliases"`
	Packs   map[string]InstalledPack `json:"packs,omitempty"`

	path string
}

const storeVersion = 1

func dataDir() string {
	if d := os.Getenv("ALIEN_HOME"); d != "" {
		return d
	}
	if d := os.Getenv("XDG_CONFIG_HOME"); d != "" {
		return filepath.Join(d, "alien")
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return ".alien"
	}
	return filepath.Join(home, ".config", "alien")
}

func storePath() string  { return filepath.Join(dataDir(), "aliases.json") }
func exportPath() string { return filepath.Join(dataDir(), "aliases.sh") }

func loadStore() (*Store, error) {
	p := storePath()
	s := &Store{Version: storeVersion, Aliases: map[string]Alias{}, path: p}

	data, err := os.ReadFile(p)
	if errors.Is(err, os.ErrNotExist) {
		return s, nil
	}
	if err != nil {
		return nil, err
	}
	if len(data) == 0 {
		return s, nil
	}
	if err := json.Unmarshal(data, s); err != nil {
		return nil, fmt.Errorf("parse %s: %w", p, err)
	}
	if s.Aliases == nil {
		s.Aliases = map[string]Alias{}
	}
	if s.Packs == nil {
		s.Packs = map[string]InstalledPack{}
	}
	s.path = p
	return s, nil
}

func (s *Store) save() error {
	if err := os.MkdirAll(filepath.Dir(s.path), 0o755); err != nil {
		return err
	}
	s.Version = storeVersion
	data, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return err
	}
	tmp := s.path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return err
	}
	if err := os.Rename(tmp, s.path); err != nil {
		return err
	}
	return s.writeShellExport()
}

// writeShellExport regenerates aliases.sh with one `alias x='y'` line per
// enabled entry. The shell integration sources this file after every alien
// invocation so new aliases are immediately active.
func (s *Store) writeShellExport() error {
	out := exportPath()
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}
	tmp := out + ".tmp"
	f, err := os.Create(tmp)
	if err != nil {
		return err
	}
	fmt.Fprintln(f, "# Generated by alien. Do not edit by hand.")
	for _, name := range s.sortedNames() {
		a := s.Aliases[name]
		if !a.Enabled {
			continue
		}
		// Shell-source entries already exist in the user's rc; re-emitting
		// them would be redundant and would conflict with their own quoting.
		if a.Source == "shell" {
			continue
		}
		fmt.Fprintf(f, "alias %s=%s\n", name, shellQuote(a.Command))
	}
	if err := f.Close(); err != nil {
		return err
	}
	return os.Rename(tmp, out)
}

func (s *Store) sortedNames() []string {
	names := make([]string, 0, len(s.Aliases))
	for n := range s.Aliases {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// shellQuote single-quotes a string for safe inclusion in `alias x=...`.
// Single quotes inside the string are escaped via the standard '\'' trick.
func shellQuote(s string) string {
	out := make([]byte, 0, len(s)+2)
	out = append(out, '\'')
	for i := 0; i < len(s); i++ {
		if s[i] == '\'' {
			out = append(out, '\'', '\\', '\'', '\'')
		} else {
			out = append(out, s[i])
		}
	}
	out = append(out, '\'')
	return string(out)
}
